version: '3.8'

services:
  postgres-monitoramento:
    image: postgres:latest
    environment:
      POSTGRES_USER: monitoramento_user
      POSTGRES_PASSWORD: monitoramento_password
      POSTGRES_DB: monitoramento_db
    ports:
      - '5432:5432'
    networks:
      - monitoramento-network

  pgadmin-monitoramento:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres-monitoramento
    networks:
      - monitoramento-network

networks:
  monitoramento-network:
    driver: bridge
